### ISSUE TITLE
Missing Overrides for Primitive Leather and Canvas Boots

### ISSUE THREAD

**Issue by Dave247** [pondobruin85/Clothing-Overhaul#1]
There are no override files for the Primitive Leather and Canvas boots, meaning that in-game they will act the same as being barefoot when using the mod. This is a big problem as the two shoes are starter boots that can be picked in the avatar creation screen. I tried creating my own override for them by copying what was written in the sandals override file but I don't know enough about creating item overrides and just ran into errors when trying to start the server.

In my opinion. all three shoes should have the same stats so to create a balanced baseline, as it's not fair to players to be an at advantage just because they picked a one over the other not knowing that it would have a gameplay effect.

**Comment by pondobruin85** [comment]
Hi Dave,
I double check this in testing, the sandals are set to false as a starter item in the file overrides, which means anyone who selects them in their avatar will not spawn in with them.  If you would like to change the stats on the sandals to be the same as barefoot, I am happy to help walk you through that.  You can find me on Eco's discord, or at my servers discord, Discord.gg/wU6aSfc4xH

Thanks for the input and I hope you are enjoying the mod :)  v0.2.0 just released.

**Comment by pondobruin85** [comment]
Closed
